name: GenerateReport
on:
  push:
    branches:
      # - develop Optional
      # - qa      Optional
      - master

  
jobs:
  GenerateReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          mvn clean install 
          mvn package 