name: GenerateReport
on:
  push:
    branches:
      # - develop Optional
      # - qa      Optional
      - master

  
jobs:
  GenerateReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Configure Sonar Properties
        run: |
            chmod 400 secrets.sh
            bash secret.sh
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
      - name: Generate Raport and Upload to SonarQube
        run: |
          mvn clean install sonar:sonar
